LITReview/LITReview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', RedirectView.as_view(pattern_name='dashboard', permanent=False)),
]
# cas où l'utilisateur n'est pas authentifié
urlpatterns += [
    path('', RedirectView.as_view(
        pattern_name='login', permanent=False), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

LITReview/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password-reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/remove-followed-user/<int:user_id>/<path:redirect_to>/',
         views.remove_followed_user, name='remove-followed-user'),

    path('profile/add-followed-user/<int:user_id>/',
         views.add_followed_user, name='add-followed-user'),
    path('abonnements/',  views.abonnements,
         name='abonnements'),
]

LITReview/dashboard/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static

urlpatterns = [
    path('', login_required(views.dashboard), name='dashboard'),
    path('posts/', login_required(views.posts), name='posts'),
    path('new-ticket/', login_required(views.create_ticket), name='new-ticket'),
    path('new-review/', login_required(views.create_review), name='new-review'),
    path('new-review/<int:ticket_id>/',
         login_required(views.create_review), name='new-review-with-ticket'),

    path('update-ticket/<int:id>/',
         login_required(views.create_ticket), name='update-ticket'),
    path('update-review/<int:id>/',
         login_required(views.create_review), name='update-review'),
    path('delete-ticket/<int:id>/', login_required(
         views.delete_ticket), name='delete-ticket'),
    path('delete-review/<int:id>/', login_required(
         views.delete_review), name='delete-review'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

LITReview/LITReview/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models


class Ticket(models.Model):
    # Your Ticket model definition goes here
    pass


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)


class UserFollows(models.Model):
    # Your UserFollows model definition goes here

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = ('user', 'followed_user', )

LITReview/dashboard/models.py
from django import forms
from django.db import models

from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Ticket(models.Model):
    t_title = models.CharField(max_length=128)
    t_description = models.TextField(max_length=2048)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)




class Review(models.Model):
    ticket = models.ForeignKey(
        to=Ticket, on_delete=models.CASCADE, blank=True, null=True)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    r_title = models.CharField(max_length=128)
    r_description = models.CharField(max_length=8192, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)

LITReview/dashboard/forms.py
from django import forms
from .models import Ticket, Review




class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['t_title', 't_description', 'image']



class MergedReviewTicketForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['ticket', 'rating', 'r_title', 'r_description']
        widgets = {
            'rating': forms.NumberInput(attrs={'min': 0, 'max': 5}),
            'r_title': forms.TextInput(attrs={'maxlength': 128}),
            'r_description': forms.Textarea(attrs={'maxlength': 8192}),
        }


class ReviewForm(forms.ModelForm):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )

    rating = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
        choices=RATING_CHOICES,
        error_messages={'required': 'Please select a rating.'},
    )

    class Meta:
        model = Review
        fields = ['ticket', 'rating', 'r_title', 'r_description']
        widgets = {
            'rating': forms.NumberInput(attrs={'min': 0, 'max': 5}),
            'r_title': forms.TextInput(attrs={'maxlength': 128}),
            'r_description': forms.Textarea(attrs={'maxlength': 8192}),
        }

LITReview/dashboard/views.py
from django.db.models import Q
from .models import Ticket
from django.shortcuts import render, redirect
from django.db.models import Count, Q
from itertools import chain
from django.shortcuts import get_object_or_404, redirect, render

from accounts.models import UserFollows
from .models import Review, Ticket
from django.db.models import Count
from django.contrib.auth.models import User
from .forms import TicketForm, ReviewForm
# Create your views here.


# def dashboard(request):
#     return render(request, 'dashboard/dashboard.html')


def create_ticket(request, id=None):
    if id:
        ticket = get_object_or_404(Ticket, pk=id, user=request.user)
        form = TicketForm(request.POST or None,
                          request.FILES or None, instance=ticket)
    else:
        form = TicketForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect('dashboard')
    return render(request, 'dashboard/create_ticket.html', {'form': form})


def delete_ticket(request, id, redirect_to='dashboard'):
    ticket = get_object_or_404(Ticket, pk=id, user=request.user)
    ticket.delete()
    return redirect(redirect_to)


def create_review(request, ticket_id=None, id=None):
    ticket = None
    print(ticket_id, id)
    if id:
        review = get_object_or_404(Review, pk=id, user=request.user)
        ticket = review.ticket
        ticket_form = TicketForm(request.POST or None,
                                 request.FILES or None, instance=ticket)
        review_form = ReviewForm(request.POST or None, instance=review)
    elif ticket_id:
        ticket = get_object_or_404(Ticket, pk=ticket_id)
        print(ticket)
        ticket_form = TicketForm(request.POST or None,
                                 request.FILES or None, instance=ticket)
        review_form = ReviewForm(request.POST or None)
    else:
        ticket_form = TicketForm(request.POST or None, request.FILES or None)
        review_form = ReviewForm(request.POST or None)
    if request.method == 'POST':
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            if ticket_form.is_valid():
                ticket = ticket_form.save(commit=False)
                ticket.user = request.user
                ticket.save()

            review.save()
            return redirect('dashboard')
    return render(request, 'dashboard/create_review.html', {'ticket_form': ticket_form, 'review_form': review_form, 'ticket': ticket})


def delete_review(request, id, redirect_to='dashboard'):
    review = get_object_or_404(Review, pk=id, user=request.user)
    review.delete()
    return redirect(redirect_to)


def dashboard(request, feed_type=None):
    followed_user_ids = UserFollows.objects.filter(
        user=request.user).values_list('followed_user__id', flat=True)
    followed_users = User.objects.filter(id__in=followed_user_ids)
    user_tickets = Ticket.objects.filter(
        user=request.user).annotate(review_count=Count('review'))
    other_tickets = Ticket.objects.filter(user__in=followed_users).exclude(
        user=request.user).annotate(review_count=Count('review'))
    remaining_tickets = Ticket.objects.exclude(Q(user__in=followed_users) | Q(
        user=request.user)).annotate(review_count=Count('review'))
    sorted_tickets = sorted(chain(user_tickets, other_tickets, remaining_tickets),
                            key=lambda instance: instance.time_created, reverse=True)
    context = {
        'feed_items': sorted_tickets,
        'show_reviews': True,
        'feed_type': 'dashboard',
        'followed_users': followed_users,
        'rating_range': range(1, 6),
    }
    return render(request, 'dashboard/dashboard.html', context)


def posts(request, feed_type=None):
    followed_user_ids = UserFollows.objects.filter(
        user=request.user).values_list('followed_user__id', flat=True)
    followed_users = User.objects.filter(id__in=followed_user_ids)

    # Fetch tickets created by the user
    user_tickets = Ticket.objects.filter(
        user=request.user).annotate(review_count=Count('review'))

    # Fetch tickets with reviews written by the user
    user_reviewed_tickets = Ticket.objects.filter(
        review__user=request.user).annotate(review_count=Count('review'))

    # Combine user_tickets and user_reviewed_tickets, removing duplicates using the "distinct" method
    combined_tickets = user_tickets | user_reviewed_tickets
    combined_tickets = combined_tickets.distinct().order_by('-time_created')

    context = {
        'feed_items': combined_tickets,
        'show_reviews': True,
        'feed_type': 'dashboard',
        'followed_users': followed_users,
        'page_title': 'posts',
        'rating_range': range(1, 6),
    }
    return render(request, 'dashboard/dashboard.html', context)

LITReview/dashboard/templates/dashboard/create_review.html
{% extends "base.html" %}
{% block title %}
    Créer une critique
{% endblock title %}
{% block nav_title %}
    Créer une critique
{% endblock nav_title %}
{% block content %}
    <form method="POST"
          enctype="multipart/form-data"
          class="create-ticket-and-review-form">
        {% csrf_token %} {% comment %} create ticket {% endcomment %}
        {% if ticket is None %}
            <div class="form-group">
                <h1>Livre/Article</h1>
                <label for="t_title" class="form-label">
                    Titre:
                </label
                >
                <br />
                <input type="text" name="t_title" class="form-control" required />
            </div>
            <div class="form-group">
                <label for="t_description" class="form-label">
                    Description:
                </label
                >
                <br />
                <textarea name="t_description" class="form-control" required></textarea>
            </div>
            <div class="form-group">
                <label for="image" class="form-label">
                    Image:
                </label
                >
                <br />
                <input type="file" name="image" accept="image/*" class="form-control" />
            </div>
        {% endif %}
        {% comment %} end create ticket {% endcomment %} {% comment %} display existing ticket from ticket_form {% endcomment %}
        {% if ticket is not None %}
            <div class="form-group">
                <h2>Vous êtes en train de proposer une réponse à:</h2>
                <br />
                <label for="id_t_title" class="form-label">
                    Titre:
                </label
                >
                <br />
                {{ ticket.t_title }}
                <br />
                <br />
                <label for="id_t_description" class="form-label">
                    Description:
                </label
                >
                <br />
                {{ ticket.t_description }}
                <br />
                <label for="id_image" class="form-label">
                    Image:
                </label
                >
                <br />
                <br />
                <img width="200"
                     height="200"
                     src="{{ ticket.image.url }}"
                     alt="image"
                     class="feed-item-image"/>
            </div>
        {% endif %}
        {% comment %} end display existing ticket {% endcomment %} {% comment %} create review {% endcomment %}
        <hr />
        <div class="form-group">
            <h1>Créer une critique</h1>
            <label for="id_rating" class="form-label">
                Évaluation:
            </label
            >
            <br />
            {{ review_form.rating }}
        </div>
        <div class="form-group">
            <label for="id_title" class="form-label">
                Titre:
            </label
            >
            <br />
            {{ review_form.r_title }}
        </div>
        <div class="form-group">
            <label for="id_body" class="form-label">
                Corps:
            </label
            >
            <br />
            {{ review_form.r_description }}
        </div>
        <button type="submit" class="btn btn-primary">Publier</button>
    </form>
    {% comment %} end create review {% endcomment %}
{% endblock content %}

LITReview/dashboard/templates/dashboard/create_ticket.html
{% extends "base.html" %}
{% block content %}
    <form method="POST"
          enctype="multipart/form-data"
          class="create-ticket-form">
        {% csrf_token %}
        <div class="form-group">
            <h1>Livre/Article</h1>
            <label for="t_title" class="form-label">
                Titre:
            </label
            >
            <br />
            <input type="text"
                   name="t_title"
                   class="form-control"
                   value="{{ form.instance.t_title }}"
                   required/>
        </div>
        <div class="form-group">
            <label for="t_description" class="form-label">
                Description:
            </label
            >
            <br />
            <textarea name="t_description" class="form-control description" required>
{{ form.instance.t_description }}</textarea
            >
        </div>
        <div class="form-group">
            <label for="image" class="form-label">
                Image:
            </label
            >
            <br />
            <input type="file" name="image" accept="image/*" class="form-control" />
            {% if form.instance.image %}<img src="{{ form.instance.image.url }}"
     alt="image"
     class="feed-item-image"/>{% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>
{% endblock content %}

LITReview/dashboard/templates/dashboard/posts.html
{% comment %} {% extends "base.html" %}
{% block title %}
    Dashboard
    {% if feed_type %}- {{ feed_type|title }}{% endif %}
{% endblock title %}
{% block nav_title %}
    {% if feed_type %}
        {{ feed_type|title }}
    {% else %}
        Dashboard
    {% endif %}
{% endblock nav_title %}
{% block content %}
    {% load static %}
    <head>
        <link rel="script" type="text/javascript" href="{% static 'js/script.js' %}"/>
    </head>
    <div class="buttons-container">
        <a href="{% url 'new-ticket' %}" class="critic-button ask">Demander une critique</a
            >
            <a href="{% url 'new-review' %}" class="critic-button create">Créer une critique</a
                >
            </div>
            <br />
            <br />
            <div class="container">
                <div class="feed-container">
                    {% for item in feed_items %}
                        {% if item.ticket %}
                            <div class="feed-item">
                                <div class="feed-item-header">
                                    <h4 class="feed-item-review-body">
                                        {% if item.user != request.user and item.user not in followed_users %}
                                            <a href="{% url 'add-followed-user' item.user.id %}" class="follow-button">
                                                <?xml version="1.0" encoding="UTF-8"?>
                                                <svg xmlns="http://www.w3.org/2000/svg"
                                                     width="24"
                                                     height="24"
                                                     viewBox="0 0 24 24">
                                                    <path d="M9.602 3.7c-1.154 1.937-.635 5.227 1.424 9.025.93 1.712.697 3.02.338 3.815-.982 2.178-3.675 2.799-6.525 3.456-1.964.454-1.839.87-1.839 4.004h-1.995l-.005-1.241c0-2.52.199-3.975 3.178-4.663 3.365-.777 6.688-1.473 5.09-4.418-4.733-8.729-1.35-13.678 3.732-13.678 3.321 0 5.97 2.117 5.97 6.167 0 3.555-1.949 6.833-2.383 7.833h-2.115c.392-1.536 2.499-4.366 2.499-7.842 0-5.153-5.867-4.985-7.369-2.458zm13.398 15.3h-3v-3h-2v3h-3v2h3v3h2v-3h3v-2z"/>
                                                </svg>
                                            </a>
                                        {% elif item.user != request.user %}
                                            <a href="{% url 'remove-followed-user' item.user.id feed_type %}"
                                               class="follow-button">
                                                <svg xmlns="http://www.w3.org/2000/svg"
                                                     width="24"
                                                     height="24"
                                                     viewBox="0 0 24 24">
                                                    <path d="M8.602 3.7c-1.154 1.937-.635 5.227 1.424 9.025.93 1.712.697 3.02.338 3.815-.982 2.178-3.675 2.799-6.525 3.456-1.964.454-1.839.87-1.839 4.004h-1.995l-.005-1.241c0-2.52.199-3.975 3.178-4.663 3.365-.777 6.688-1.473 5.09-4.418-4.733-8.729-1.35-13.678 3.732-13.678 3.321 0 5.97 2.117 5.97 6.167 0 3.555-1.949 6.833-2.383 7.833h-2.115c.392-1.536 2.499-4.366 2.499-7.842 0-5.153-5.867-4.985-7.369-2.458zm15.398 15.8c0 2.485-2.017 4.5-4.5 4.5s-4.5-2.015-4.5-4.5 2.017-4.5 4.5-4.5 4.5 2.015 4.5 4.5zm-2-.5h-5v1h5v-1z"/>
                                                </svg>
                                            </a>
                                        {% endif %}
                                        {{ item.user.username }}
                                        {% if not item.review_set.exists and item.user != request.user %}a demandé une critique pour{% endif %}
                                        :
                                    </h4>
                                    {% if item.review_set.exists %}
                                        <h3 class="feed-item-title">
                                            {{ item.t_title }}
                                            <br />
                                        </h3>
                                        <h3>
                                            {{ item.review_count }}
                                            {% if item.review_count != 1 %}
                                                reviews
                                            {% else %}
                                                review
                                            {% endif %}
                                        </h3>
                                    {% else %}
                                        <h3 class="feed-item-title">{{ item.t_title }}</h3>
                                    {% endif %}
                                    <p class="feed-item-description">{{ item.t_description }}</p>
                                    {% if item.user == request.user %}
                                        <a href="{% url 'update-ticket' item.id %}" class="update-button">
                                            <?xml version="1.0" encoding="UTF-8"?>
                                            <svg href="{% url 'update-ticket' item.id %}"
                                                 xmlns="http://www.w3.org/2000/svg"
                                                 width="20"
                                                 height="20"
                                                 viewBox="0 0 20 20">
                                                <title>edit</title>
                                                <path d="M16.77 8l1.94-2a1 1 0 0 0 0-1.41l-3.34-3.3a1 1 0 0 0-1.41 0L12 3.23zm-5.81-3.71L1 14.25V19h4.75l9.96-9.96-4.75-4.75z" />
                                            </svg>
                                        </a>
                                        <a href="{% url 'delete-ticket' item.id %}" class="update-button">
                                            <svg width="24"
                                                 height="24"
                                                 xmlns="http://www.w3.org/2000/svg"
                                                 fill-rule="evenodd"
                                                 clip-rule="evenodd">
                                                <path d="M19 24h-14c-1.104 0-2-.896-2-2v-16h18v16c0 1.104-.896 2-2 2m-9-14c0-.552-.448-1-1-1s-1 .448-1 1v9c0 .552.448 1 1 1s1-.448 1-1v-9zm6 0c0-.552-.448-1-1-1s-1 .448-1 1v9c0 .552.448 1 1 1s1-.448 1-1v-9zm6-5h-20v-2h6v-1.5c0-.827.673-1.5 1.5-1.5h5c.825 0 1.5.671 1.5 1.5v1.5h6v2zm-12-2h4v-1h-4v1z"/>
                                            </svg>
                                        </a>
                                    {% endif %}
                                </div>
                                <div class="button-image-section">
                                    <a href="{% url 'new-review-with-ticket' ticket_id=item.id %}"
                                       class="review-button">Créer une critique</a
                                        >
                                        <br />
                                        {% if item.image %}
                                            <img width="200"
                                                 height="200"
                                                 src="{{ item.image.url }}"
                                                 alt="{{ item.t_title }}"
                                                 class="feed-item-image"/>
                                        {% endif %}
                                        {% if item.review_set %}<br />{% endif %}
                                    </div>
                                </div>
                            {% else %}
                                {# Handle reviews here #}
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
{% endblock content %} {% endcomment %}